#// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#// SPDX-License-Identifier: Apache-2.0
# Assisted Log Enabler for AWS - Find resources that are not logging, and turn them on.
# Joshua "DozerCat" McKiddy - Customer Incident Response Team (CIRT) - AWS
# This sample template is for creating an IAM Role within child accounts, for the purpose of running Assisted Log Enabler across a multi-account environment.


AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates the baseline IAM Role and Policy, for use with Assisted Log Enabler across multiple accounts.
Parameters:
  AssistedLogEnablerPolicyName:
    Description: Please name the policy that will be used with the Assisted Log Enabler IAM Role.
    Type: String
    Default: AssistedLogEnabler_IAM_Policy
  SourceAccountNumber:
    Description: Please provide the source account that Assisted Log Enabler will be running from.
    Type: String
  OrgId:
    Description: Please provide the AWS Organization ID (e.g. o-abcdefg123)
    Type: String



Resources:
  AssistedLogEnablerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref AssistedLogEnablerPolicyName
      Path: /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogDelivery
              - ec2:CreateFlowLogs
              - ec2:DescribeVpcs
              - s3:PutLifecycleConfiguration
              - ec2:DescribeFlowLogs
              - s3:PutBucketPolicy
              - s3:CreateBucket
              - s3:GetBucketPolicy
              - cloudtrail:DescribeTrails
              - cloudtrail:CreateTrail
              - s3:PutObject
              - cloudtrail:StartLogging
              - eks:UpdateClusterConfig
              - eks:ListClusters
              - route53resolver:ListResolverQueryLogConfigAssociations
              - route53resolver:CreateResolverQueryLogConfig
              - route53resolver:AssociateResolverQueryLogConfig
              - route53resolver:TagResource
              - s3:PutBucketLogging
              - s3:GetBucketLogging
              - s3:ListBucket
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
              - s3:GetBucketAcl
              - s3:PutBucketAcl
              - s3:PutBucketPublicAccessBlock
              - s3:PutBucketLifecycleConfiguration
              - elb:DescribeLoadBalancers
              - elb:DescribeLoadBalancerAttributes
              - elb:ModifyLoadBalancerAttributes
              - elbv2:DescribeLoadBalancers
              - elbv2:DescribeLoadBalancerAttributes
              - elbv2:ModifyLoadBalancerAttributes
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeLoadBalancerAttributes
              - elasticloadbalancing:ModifyLoadBalancerAttributes
              - eks:ListClusters
              - ec2:CreateTags
              - guardduty:ListDetectors
              - guardduty:ListInvitations
              - guardduty:AcceptAdministratorInvitation
              - guardduty:TagResource
              - guardduty:CreateDetector
            Resource: '*'
            Condition:
              StringEquals:
                'aws:PrincipalOrgId': !Ref OrgId
          - Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
            Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/route53resolver.amazonaws.com/AWSServiceRoleForRoute53Resolver
            Condition:
              StringLike:
                'iam:AWSServiceName': 'route53resolver.amazonaws.com'
          - Effect: Allow
            Action:
              - route53resolver:ListResolverQueryLogConfigs
              - route53resolver:ListTagsForResource
              - route53resolver:ListResolverQueryLogConfigAssociations
              - route53resolver:DisassociateResolverQueryLogConfig
              - route53resolver:DeleteResolverQueryLogConfig
            Resource: '*'
            Condition:
              StringEquals:
                'aws:PrincipalOrgId': !Ref OrgId

  AssistedLogEnablerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Assisted_Log_Enabler_IAM_Role
      Description: Role to be assumed for running Assisted Log Enabler across a multi-account environment.
      ManagedPolicyArns:
        - Ref: AssistedLogEnablerPolicy
      MaxSessionDuration: 3600
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
              - !Ref SourceAccountNumber
            Action:
              - sts:AssumeRole
