name: Lint code

on:
  push:
  pull_request:
    branches-ignore: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Set up Python 3.9
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
      with:
        python-version: 3.9
    - name: Run pre-commit
      uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
